#
# File:- Makefile 
# written by Manish Regmi (manish_regmi@hotmail.com)
#
# Makefile for easy compilation.:-)



OPTIONS = -Wall -O2
INCLS = -I"../"

CC = gcc
AS = as
LD = ld
MAKE = mingw32-make 
MAKEFILE = -f Makefile.win32
REMOVE = del

	
OBJS = lvm.o

all: lvms.o
.c.o:
	$(CC) -c $(OPTIONS) $(INCLS) $< -o $@

.o: $(OBJS)
	$(LD) -r -o lvms.o $(OBJS)
clear:
	$(REMOVE) *.c~ *~ *.o

