obj-m := kvm.o kvm-intel.o kvm-amd.o
kvm-objs := kvm_main.o x86.o mmu.o emulate.o ../anon_inodes.o irq.o i8259.o \
	 lapic.o ioapic.o preempt.o i8254.o coalesced_mmio.o irq_comm.o \
	 timer.o eventfd.o assigned-dev.o \
	 ../external-module-compat.o ../request-irq-compat.o
ifeq ($(CONFIG_IOMMU_API),y)
kvm-objs += iommu.o
endif
kvm-intel-objs := vmx.o vmx-debug.o
kvm-amd-objs := svm.o

kvm-objs += ../srcu.o

CFLAGS_kvm_main.o = -DKVM_MAIN
