#
# File:- Makefile 
# written by Manish Regmi (manish_regmi@hotmail.com)
#
# Makefile for easy compilation.:-)



OPTIONS = -Wall -O2
INCLS = -I. -I../ -I../platform/ 

CC = gcc
AS = as
LD = ld
MAKE = make 
MAKEFILE = -f Makefile.unix
REMOVE = rm

	
OBJS = ext2io.o inode.o mount.o namei.o

all: ext2.o
.c.o:
	$(CC) -c $(OPTIONS) $(INCLS) $< -o $@

ext2.o: $(OBJS)
	$(LD) -r -o ext2.o $(OBJS)
clear:
	$(REMOVE) *.c~ *~ *.o

